name: Deploy

on:
  push:
    tags:
      - "**"

jobs:
  build:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      TRACKER_QUEUE: TMP
      TRACKER_ORG: 6461097
      TRACKER_TOKEN: ${{ secrets.TRACKER_OAUTH_TOKEN }}
      APP: ${{ github.event.repository.name }}
      REPO: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Run meta.sh script
        run: |
          chmod +wx ./actions/meta.sh
          ./actions/meta.sh

      - name: Run Jest tests
        run: |
          npm ci
          npm run testOutput

      - name: Run docker.sh script
        run: |
          chmod +x ./actions/docker.sh
          ./actions/docker.sh

      - name: Update yandex.tracker info
        run: npm run info
