name: Build

on:
  push:
    branches:
    - main
    tags:
      - "**"

jobs:
  build:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      APP: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v2
      - uses: olegtarasov/get-tag@v2.1.1
      - name: Run docker.sh script
        run: |
          chmod +x ./actions/docker.sh
          ./actions/docker.sh
