name: Build

on:
  push:
    branches:
      - main
    tags:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Run docker.sh script
        run: chmod +x ./actions/docker.sh